### PR TITLE
Modifications

### LINKED ISSUE #7: Functionality to create posts by certain users
A functionality needs to be added for certain users(admins) to create, edit and publish notices.

### PR DESCRIPTION
**Pull request by Yathartha22**
- [x] Added capability for admin to create notice

- [x] Added Category field, so that notices can be displayed as per their category

- [x] Notices to be displayed only to authenticated user(FIXED)

- [x] Creating admins

fixes: #7 

**Note**: As per now login using username, I will provide login via other field in next PR

@shubham9411 have look over the changes in the frontend.

### CODE REVIEW

**Comment by shubham9411** [comment]
Can you provide the APIs endpoints and their responses for using them in app.

**Comment by Yathartha22** [comment]
Sorry I forgot
Creating new notices:
[http://localhost:8000/api/v1/addnotices/](http://localhost:8000/api/v1/addnotices/)

**Comment by Yathartha22** [comment]
Adding admin
[http://localhost:8000/api/v1/auth/addadmin/](http://localhost:8000/api/v1/auth/addadmin/)

**Comment by shubham9411** [comment]
As per now we are using username for login but i think you forgot to change the form entry for `email` to `username`. Currently the post request is like `{email: 'username', password: '123456'}` working but i think it should be changed to `{username: 'username', password: '123456'}`. My ques is are we going to use both is auth `username` and `email` or just the username?
If not and in future we will use only username, can I make a pull request regarding this change?

**Comment by Yathartha22** [comment]
Yes I forgot to change that. :D , sure if you like you can create a PR, otherwise I will fix this in next PR.

> My ques is are we going to use both is auth username and email or just the username?

I guess we agreed to another field - phone number-  ;) , nevertheless I am +1 with username.

**Pull request merged**
